{
  "_args": [
    [
      "safe-event-emitter@1.0.1",
      "C:\\Users\\Owner\\Resilio Sync\\Synced Docs\\Academic\\CWRU Bootcamp\\Projects\\OpenLease\\ui\\node_modules\\ganache-core"
    ]
  ],
  "_from": "safe-event-emitter@1.0.1",
  "_id": "safe-event-emitter@1.0.1",
  "_inBundle": false,
  "_integrity": "sha512-e1wFe99A91XYYxoQbcq2ZJUWurxEyP8vfz7A7vuUe1s95q8r5ebraVaA1BukYJcpM6V16ugWoD9vngi8Ccu5fg==",
  "_location": "/ganache-core/safe-event-emitter",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "safe-event-emitter@1.0.1",
    "name": "safe-event-emitter",
    "escapedName": "safe-event-emitter",
    "rawSpec": "1.0.1",
    "saveSpec": null,
    "fetchSpec": "1.0.1"
  },
  "_requiredBy": [
    "/ganache-core/json-rpc-engine"
  ],
  "_resolved": "https://registry.npmjs.org/safe-event-emitter/-/safe-event-emitter-1.0.1.tgz",
  "_spec": "1.0.1",
  "_where": "C:\\Users\\Owner\\Resilio Sync\\Synced Docs\\Academic\\CWRU Bootcamp\\Projects\\OpenLease\\ui\\node_modules\\ganache-core",
  "author": "",
  "dependencies": {
    "events": "^3.0.0"
  },
  "description": "An `EventEmitter` that isolates the emitter from errors in handlers. If an error is thrown in a handler it is caught and re-thrown inside of a `setTimeout` so as to not interupt the emitter's code flow.",
  "license": "ISC",
  "main": "index.js",
  "name": "safe-event-emitter",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "1.0.1"
}
